# Generated by Django 5.0.6 on 2024-07-05 17:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('pat_name', models.CharField(max_length=300)),
                ('med_name', models.CharField(max_length=300)),
                ('dose', models.CharField(max_length=300)),
                ('by', models.CharField(max_length=300)),
                ('period', models.CharField(max_length=300)),
                ('dx_code', models.CharField(max_length=300)),
                ('refill', models.IntegerField()),
                ('label', models.BooleanField()),
                ('generic', models.BooleanField()),
                ('providerinfo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portal.providerinfo')),
            ],
        ),
    ]
