# Generated by Django 5.0.6 on 2024-07-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_remove_medprescription_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medprescription',
            name='supply',
            field=models.CharField(choices=[('30 day', '30 day'), ('90 day', '90 day')], default='30 day', max_length=300),
        ),
    ]
