# Generated by Django 5.0.6 on 2024-07-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_medprescription_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medprescription',
            name='supply',
            field=models.CharField(max_length=300),
        ),
    ]
