# Generated by Django 5.0.6 on 2024-07-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='medprescription',
            name='add_instructions',
            field=models.TextField(blank=True),
        ),
    ]
