# Generated by Django 5.0.6 on 2024-07-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(blank=True, editable=False, max_length=300)),
                ('role', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('license_number', models.CharField(blank=True, max_length=300, null=True)),
                ('npi_number', models.CharField(blank=True, max_length=300, null=True)),
                ('group', models.CharField(default='Administrator', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(blank=True, editable=False, max_length=300)),
                ('role', models.CharField(choices=[('Doctor', 'Doctor'), ('Physician Assistant', 'Physician Assistant'), ('Nurse Practitioner', 'Nurse Practitioner'), ('Nurse', 'Nurse'), ('Nursing Aide', 'Nursing Aide'), ('Therapist', 'Therapist'), ('Technician', 'Technician')], max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('license_number', models.CharField(max_length=300)),
                ('npi_number', models.CharField(max_length=300)),
                ('group', models.CharField(default='Provider', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(blank=True, editable=False, max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('bdate', models.DateField()),
                ('age', models.IntegerField(blank=True, editable=False)),
                ('gender', models.CharField(max_length=300)),
                ('hist', models.TextField()),
                ('group', models.CharField(default='Patient', editable=False, max_length=100)),
                ('provider', models.ManyToManyField(blank=True, to='portal.providerinfo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='patientinfo',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 0)), name='age_non_negative'),
        ),
    ]
