# Generated by Django 5.0.6 on 2024-07-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerinfo',
            name='dea_number',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
