# Generated by Django 5.0.6 on 2024-07-04 16:15

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PtContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetandnumber', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('zip', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('phone1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('phone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
                ('patinfo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portal.patientinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PtEmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact', models.CharField(max_length=300)),
                ('relation', models.CharField(max_length=300)),
                ('streetandnumber', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(blank=True, max_length=300, null=True)),
                ('state', models.CharField(blank=True, max_length=300, null=True)),
                ('zip', models.CharField(blank=True, max_length=300, null=True)),
                ('country', models.CharField(blank=True, max_length=300, null=True)),
                ('phone1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('phone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
                ('patinfo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portal.patientinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PtInsuranceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_company', models.CharField(max_length=300)),
                ('groupandnumber', models.CharField(max_length=300)),
                ('streetandnumber', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('zip', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('fax', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
                ('patinfo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portal.patientinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PtVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('reason', models.TextField()),
                ('dx', models.TextField()),
                ('px', models.TextField()),
                ('lx', models.TextField()),
                ('prx', models.TextField()),
                ('patinst', models.TextField()),
                ('patinfo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portal.patientinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PtVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('height', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('temperature', models.FloatField()),
                ('resp_rate', models.IntegerField()),
                ('pulse', models.IntegerField()),
                ('oxy_sat', models.FloatField()),
                ('blood_pressure', models.CharField(max_length=100)),
                ('patinfo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portal.patientinfo')),
            ],
        ),
    ]
