# Generated by Django 5.0.6 on 2024-07-04 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PtContactInfo',
            new_name='ContactInfo',
        ),
        migrations.RenameModel(
            old_name='PtEmergencyContact',
            new_name='EmergencyContact',
        ),
        migrations.RenameModel(
            old_name='PtInsuranceInfo',
            new_name='InsuranceInfo',
        ),
        migrations.RenameModel(
            old_name='PtVisit',
            new_name='Visit',
        ),
        migrations.RenameModel(
            old_name='PtVitals',
            new_name='Vitals',
        ),
    ]
